In [1]:
import sys
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[1:3]

array([2, 3])

In [8]:
a[1:-1]

array([2, 3])

In [9]:
a[2:]

array([3, 4])

<hr />

### Multiindexing ###
Podemos acceder a multiples elementos separandolos al igual que en una lista de python normal, o podemos usar multiindexing que crea un nuevo array.

In [10]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [11]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Array Types

In [12]:
a.dtype

dtype('int64')

In [13]:
b.dtype

dtype('float64')

In [14]:
c = np.array(['a', 'b', 'c'])

In [15]:
c.dtype

dtype('<U1')

In [16]:
d = np.array([{'a': 1}, sys])

In [17]:
d.dtype

dtype('O')

<hr />

### Dimensions and Shapes (Matrices)

In [18]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [19]:
A.shape   # Cuantas filas y columnas tiene. (dos filas y tres columnas)

(2, 3)

In [20]:
A.ndim    # Cuantas dimensiones tiene. (dos dimensiones, vertical y horizontal)

2

In [21]:
A.size    # Total de elementos. (seis elementos)

6

In [22]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [23]:
B.shape

(2, 2, 3)

In [24]:
B.ndim

3

In [25]:
B.size

12

**Hay que tener mucho cuidado al crear este tipo de arrays ya que si no coinciden entre si los array anidados entonces el array se transforma en tipo "objeto".**

In [26]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4]
    ]
])

/tmp/ipykernel_5937/1156286633.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [27]:
C.dtype

dtype('O')

In [28]:
C.shape

(2,)

In [29]:
C.size

2

<hr />

### Indexing and Slicing Matrices

In [30]:
# Square Matrix
A = np.array([
#    0  1  2
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [31]:
A[1]

array([4, 5, 6])

In [32]:
A[1][0]

4

In [33]:
A[1, 0]

4

In [34]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [36]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [37]:
A[:2, 2:]

array([[3],
       [6]])

In [38]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
A[1] = np.array([10, 10, 10])

In [40]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [41]:
A[2] = 99

In [42]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [43]:
A[2] = [11, 12, 13]

In [44]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [11, 12, 13]])

<hr/>

### Summary Statistics

In [45]:
a = np.array([1, 2, 3, 4])

In [46]:
a.sum()

10

In [47]:
a.mean()

2.5

In [48]:
a.std()

1.118033988749895

In [49]:
a.var()

1.25

In [50]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [51]:
A.sum()

45

In [52]:
A.mean()

5.0

In [53]:
A.std()

2.581988897471611

In [54]:
A.sum(axis=0) # Columns

array([12, 15, 18])

In [55]:
A.sum(axis=1) # Rows

array([ 6, 15, 24])

In [56]:
A.mean(axis=0)

array([4., 5., 6.])

In [57]:
A.mean(axis=1)

array([2., 5., 8.])

In [58]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [59]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

And [many more](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)...

<hr/>

### Broadcasting and Vectorized operations

Las operaciones vectorizadas son operaciones computadas en un lenguaje de bajo nivel para acelerar la velocidad de procesamiento, en el caso de Numpy ese lenguaje es C.

In [60]:
a = np.arange(4)

In [61]:
a

array([0, 1, 2, 3])

In [62]:
a + 10

array([10, 11, 12, 13])

In [63]:
a * 10 

array([ 0, 10, 20, 30])

In [64]:
a

array([0, 1, 2, 3])

In [65]:
a += 100

In [66]:
a

array([100, 101, 102, 103])

In [67]:
l = [0, 1, 2, 3]

In [68]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [69]:
a = np.arange(4)

In [70]:
a

array([0, 1, 2, 3])

In [71]:
b = np.array([10, 10, 10, 10])

In [72]:
b

array([10, 10, 10, 10])

In [73]:
a + b

array([10, 11, 12, 13])

In [74]:
a * b

array([ 0, 10, 20, 30])

---

### Boolean Arrays

*(Tambien conocidos como mascaras)*

In [75]:
a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a[0], a[-1]

(0, 3)

In [78]:
a[[0, -1]]

array([0, 3])

In [79]:
a[[True, False, False, True]]

array([0, 3])

In [80]:
a >= 2

array([False, False,  True,  True])

In [81]:
a[a >= 2]

array([2, 3])

In [82]:
a.mean()

1.5

In [83]:
a[a > a.mean()]

array([2, 3])

In [84]:
a[~(a > a.mean())]  # (~) Operador de negacion. Los valores que NO son mayores que el promedio.

array([0, 1])

In [85]:
a[(a == 0) | (a == 1)] # (|) Operador OR de numpy.

array([0, 1])

In [86]:
a[(a <= 2) & (a % 2 == 0)] # (&) Operador AND de numpy.

array([0, 2])

In [87]:
A = np.random.randint(100, size=(3, 3))

In [88]:
A

array([[45, 20, 47],
       [32, 68, 92],
       [61, 65, 35]])

In [89]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([45, 47, 68, 61, 35])

In [90]:
A > 30

array([[ True, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [91]:
A[A > 30]

array([45, 47, 32, 68, 92, 61, 65, 35])

---

### Linear Algebra

**Numpy** contiene operadores predefinidos para las operaciones basicas de algebra lineal de manera vectorizada, por lo que son extremadamente veloces.

In [92]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [93]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [94]:
A.dot(B)  # Dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [95]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [96]:
B.T   # Transposing the array

array([[6, 4, 2],
       [5, 3, 1]])

In [97]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

---

### Size of objects in Memory

#### **Int, floats**

In [99]:
# Un integer(entero) en Python es > 24 bytes
sys.getsizeof(1)

28

In [100]:
# Los Longs son incluso mas grandes
sys.getsizeof(10**100)

72

In [101]:
# En Numpy los tamaños son menores
np.dtype(int).itemsize

8

In [102]:
np.dtype(float).itemsize

8

#### **Las listas son incluso más grandes**

In [103]:
# Lista de un elemento
sys.getsizeof([1])

64

In [104]:
# Array de un elemento
np.array([1]).nbytes

8

#### **La performance tambien es importante**

In [105]:
l = list(range(1000))

In [106]:
a = np.arange(1000)

In [107]:
%time np.sum(a ** 2)

CPU times: user 105 µs, sys: 29 µs, total: 134 µs
Wall time: 105 µs


332833500

In [108]:
%time sum([x ** 2 for x in l])

CPU times: user 505 µs, sys: 139 µs, total: 644 µs
Wall time: 657 µs


332833500

---

### Funciones utiles de Numpy

#### `random`

In [109]:
np.random.random(size=2)

array([0.45599457, 0.86725692])

In [110]:
np.random.normal(size=2)

array([-0.13465738,  0.43699368])

In [111]:
np.random.rand(2, 4)

array([[0.85744217, 0.36734566, 0.88486673, 0.90325572],
       [0.96067217, 0.61617561, 0.70062555, 0.19625701]])

---

#### `arange`

In [112]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [114]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

---

#### `reshape`

In [115]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [116]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

---

#### `linspace`

In [117]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [118]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [119]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

---

#### `zeros`, `ones`, `empty`

In [120]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [121]:
np.zeros([3, 3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [122]:
np.zeros([3, 3], dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [123]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [124]:
np.ones([3, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [125]:
np.ones([3, 3], dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [126]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [127]:
np.empty([2, 2])

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

---

#### `identity` and `eye`

In [128]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [131]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [133]:
'Hello World'[6]

'W'